name: callvis_movies
description: Un'app per sfogliare film usando TMDb API.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5

flutter:
  uses-material-design: true
